Use Staging

SELECT TOP 0 * INTO Application.StateProvinces FROM WideWorldImporters.Application.StateProvinces
SELECT TOP 0 * INTO Application.Cities FROM WideWorldImporters.Application.Cities
SELECT TOP 0 * INTO Application.SystemParameters FROM WideWorldImporters.Application.SystemParameters
SELECT TOP 0 * INTO Application.People FROM WideWorldImporters.Application.People
SELECT TOP 0 * INTO Application.Countries FROM WideWorldImporters.Application.Countries
SELECT TOP 0 * INTO Application.DeliveryMethods FROM WideWorldImporters.Application.DeliveryMethods
SELECT TOP 0 * INTO Application.PaymentMethods FROM WideWorldImporters.Application.PaymentMethods
SELECT TOP 0 * INTO Application.TransactionTypes FROM WideWorldImporters.Application.TransactionTypes
SELECT TOP 0 * INTO Purchasing.SupplierCategories FROM WideWorldImporters.Purchasing.SupplierCategories
SELECT TOP 0 * INTO Purchasing.PurchaseOrderLines FROM WideWorldImporters.Purchasing.PurchaseOrderLines
SELECT TOP 0 * INTO Purchasing.SupplierTransactions FROM WideWorldImporters.Purchasing.SupplierTransactions
SELECT TOP 0 * INTO Purchasing.Suppliers FROM WideWorldImporters.Purchasing.Suppliers
SELECT TOP 0 * INTO Purchasing.PurchaseOrders FROM WideWorldImporters.Purchasing.PurchaseOrders
SELECT TOP 0 * INTO Sales.Orders FROM WideWorldImporters.Sales.Orders
SELECT TOP 0 * INTO Sales.Customers FROM WideWorldImporters.Sales.Customers
SELECT TOP 0 * INTO Sales.InvoiceLines FROM WideWorldImporters.Sales.InvoiceLines
SELECT TOP 0 * INTO Sales.CustomerTransactions FROM WideWorldImporters.Sales.CustomerTransactions
SELECT TOP 0 * INTO Sales.OrderLines FROM WideWorldImporters.Sales.OrderLines
SELECT TOP 0 * INTO Sales.SpecialDeals FROM WideWorldImporters.Sales.SpecialDeals
SELECT TOP 0 * INTO Sales.BuyingGroups FROM WideWorldImporters.Sales.BuyingGroups
SELECT TOP 0 * INTO Sales.Invoices FROM WideWorldImporters.Sales.Invoices
SELECT TOP 0 * INTO Sales.CustomerCategories FROM WideWorldImporters.Sales.CustomerCategories
SELECT TOP 0 * INTO Warehouse.StockItemHoldings FROM WideWorldImporters.Warehouse.StockItemHoldings
SELECT TOP 0 * INTO Warehouse.StockItems FROM WideWorldImporters.Warehouse.StockItems
SELECT TOP 0 * INTO Warehouse.PackageTypes FROM WideWorldImporters.Warehouse.PackageTypes
SELECT TOP 0 * INTO Warehouse.StockGroups FROM WideWorldImporters.Warehouse.StockGroups
SELECT TOP 0 * INTO Warehouse.StockItemStockGroups FROM WideWorldImporters.Warehouse.StockItemStockGroups
SELECT TOP 0 * INTO Warehouse.Colors FROM WideWorldImporters.Warehouse.Colors
SELECT TOP 0 * INTO Warehouse.StockItemTransactions FROM WideWorldImporters.Warehouse.StockItemTransactions
SELECT TOP 0 * INTO Warehouse.ColdRoomTemperatures FROM WideWorldImporters.Warehouse.ColdRoomTemperatures
SELECT TOP 0 * INTO Warehouse.VehicleTemperatures FROM WideWorldImporters.Warehouse.VehicleTemperatures
SELECT TOP 0 * INTO Website.Customers FROM WideWorldImporters.Website.Customers
SELECT TOP 0 * INTO Website.VehicleTemperatures FROM WideWorldImporters.Website.VehicleTemperatures
SELECT TOP 0 * INTO Website.Suppliers FROM WideWorldImporters.Website.Suppliers